# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BTtestRoutine <- function(X, r_max, alpha, BT1, R) {
    .Call(`_BTtest_BTtestRoutine`, X, r_max, alpha, BT1, R)
}

BaiIPCRoutine <- function(X, r_max) {
    .Call(`_BTtest_BaiIPCRoutine`, X, r_max)
}

