# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Obtain a standardization factor for the eigenvalues according to Eq. 18
NULL

nFactors <- function(X, rmax, alpha) {
    .Call(`_BTtest_nFactors`, X, rmax, alpha)
}

